server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dd_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
oss:
  accessKey: 9UNe7B7Q5eE_sV_DPizJIMtJxtfcEOSwFoPuplsQ
  secretKey: y9BBPmBqWivtnLDiqCN8F63qbr_n2y9T_s1OpSol
  bucket: dd-blog


